version: "3.5"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./public:/var/www/public
      - ./storage:/var/www/storage
      - ./docker/local/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/local/nginx/logs:/var/log/nginx/
    ports:
      - "8000:80"
    restart: unless-stopped
    container_name: auth_microservice_nginx

  app:
    build:
      context: .
      dockerfile: docker/local/app/Dockerfile
    volumes:
      - ./public:/var/www/public
      - ./storage:/var/www/storage
    restart: unless-stopped
    container_name: auth_microservice_app
    entrypoint: ["sh", "-c", "./docker/entrypoint.sh"]

  postgres:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
    container_name: auth_microservice_postgres

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8888:80"
    restart: unless-stopped
    container_name: auth_microservice_pgadmin

