version: "3.5"

services:
  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www
      - ./docker/local/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8000:80"
    restart: unless-stopped
    container_name: auth_microservice_nginx

  php:
    build:
      context: docker/local/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    restart: unless-stopped
    container_name: auth_microservice_php

  postgres:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
    container_name: auth_microservice_postgres
